export type TypographyStyle = {
  token: string;
  className: string;
  font: string;
  weight: string;
  size: string;
  lineHeight: string;
  preview: string;
  tnum?: boolean;
};

export const displayStyles: TypographyStyle[] = [
  {
    token: "Display/Large Bold",
    className: "text-display-large-bold",
    font: "Roboto Bold",
    weight: "700",
    size: "36px",
    lineHeight: "44px",
    preview: "$12,847.50",
    tnum: true,
  },
  {
    token: "Display/Large Medium",
    className: "text-display-large-medium",
    font: "Roboto Medium",
    weight: "500",
    size: "36px",
    lineHeight: "44px",
    preview: "$12,847.50",
    tnum: true,
  },
  {
    token: "Display/Large Regular",
    className: "text-display-large-regular",
    font: "Roboto Regular",
    weight: "400",
    size: "36px",
    lineHeight: "44px",
    preview: "$12,847.50",
    tnum: true,
  },
  {
    token: "Display/Small Bold",
    className: "text-display-small-bold",
    font: "Roboto Bold",
    weight: "700",
    size: "28px",
    lineHeight: "36px",
    preview: "1  2  3  4  5",
    tnum: true,
  },
  {
    token: "Display/Small Medium",
    className: "text-display-small-medium",
    font: "Roboto Medium",
    weight: "500",
    size: "28px",
    lineHeight: "36px",
    preview: "1  2  3  4  5",
    tnum: true,
  },
  {
    token: "Display/Small Regular",
    className: "text-display-small-regular",
    font: "Roboto Regular",
    weight: "400",
    size: "28px",
    lineHeight: "36px",
    preview: "1  2  3  4  5",
    tnum: true,
  },
];

export const headingStyles: TypographyStyle[] = [
  {
    token: "Heading/H1 Bold",
    className: "text-heading-h1-bold",
    font: "Poppins Bold",
    weight: "700",
    size: "40px",
    lineHeight: "48px",
    preview: "H1 Sample",
  },
  {
    token: "Heading/H1 Medium",
    className: "text-heading-h1-medium",
    font: "Poppins Medium",
    weight: "500",
    size: "40px",
    lineHeight: "48px",
    preview: "H1 Sample",
  },
  {
    token: "Heading/H1 Regular",
    className: "text-heading-h1-regular",
    font: "Poppins Regular",
    weight: "400",
    size: "40px",
    lineHeight: "48px",
    preview: "H1 Sample",
  },
  {
    token: "Heading/H2 Bold",
    className: "text-heading-h2-bold",
    font: "Poppins Bold",
    weight: "700",
    size: "24px",
    lineHeight: "32px",
    preview: "H2 Section Title",
  },
  {
    token: "Heading/H2 Medium",
    className: "text-heading-h2-medium",
    font: "Poppins Medium",
    weight: "500",
    size: "24px",
    lineHeight: "32px",
    preview: "H2 Section Title",
  },
  {
    token: "Heading/H2 Regular",
    className: "text-heading-h2-regular",
    font: "Poppins Regular",
    weight: "400",
    size: "24px",
    lineHeight: "32px",
    preview: "H2 Section Title",
  },
  {
    token: "Heading/H3 Bold",
    className: "text-heading-h3-bold",
    font: "Poppins Bold",
    weight: "700",
    size: "20px",
    lineHeight: "28px",
    preview: "H3 Subheading",
  },
  {
    token: "Heading/H3 Medium",
    className: "text-heading-h3-medium",
    font: "Poppins Medium",
    weight: "500",
    size: "20px",
    lineHeight: "28px",
    preview: "H3 Subheading",
  },
  {
    token: "Heading/H3 Regular",
    className: "text-heading-h3-regular",
    font: "Poppins Regular",
    weight: "400",
    size: "20px",
    lineHeight: "28px",
    preview: "H3 Subheading",
  },
];

export const bodyStyles: TypographyStyle[] = [
  {
    token: "Body/Large Bold",
    className: "text-body-large-bold",
    font: "Roboto Bold",
    weight: "700",
    size: "16px",
    lineHeight: "24px",
    preview: "Body Large Sample",
  },
  {
    token: "Body/Large Medium",
    className: "text-body-large-medium",
    font: "Roboto Medium",
    weight: "500",
    size: "16px",
    lineHeight: "24px",
    preview: "Body Large Sample",
  },
  {
    token: "Body/Large Regular",
    className: "text-body-large-regular",
    font: "Roboto Regular",
    weight: "400",
    size: "16px",
    lineHeight: "24px",
    preview: "Body Large Sample",
  },
  {
    token: "Body/Small Bold",
    className: "text-body-small-bold",
    font: "Roboto Bold",
    weight: "700",
    size: "14px",
    lineHeight: "20px",
    preview: "Body Small Sample",
  },
  {
    token: "Body/Small Medium",
    className: "text-body-small-medium",
    font: "Roboto Medium",
    weight: "500",
    size: "14px",
    lineHeight: "20px",
    preview: "Body Small Sample",
  },
  {
    token: "Body/Small Regular",
    className: "text-body-small-regular",
    font: "Roboto Regular",
    weight: "400",
    size: "14px",
    lineHeight: "20px",
    preview: "Body Small Sample",
  },
];

export const dataStyles: TypographyStyle[] = [
  {
    token: "Data/Large Bold",
    className: "text-data-large-bold",
    font: "Roboto Bold",
    weight: "700",
    size: "16px",
    lineHeight: "24px",
    preview: "TXN-2024-001847",
    tnum: true,
  },
  {
    token: "Data/Large Medium",
    className: "text-data-large-medium",
    font: "Roboto Medium",
    weight: "500",
    size: "16px",
    lineHeight: "24px",
    preview: "TXN-2024-001847",
    tnum: true,
  },
  {
    token: "Data/Large Regular",
    className: "text-data-large-regular",
    font: "Roboto Regular",
    weight: "400",
    size: "16px",
    lineHeight: "24px",
    preview: "TXN-2024-001847",
    tnum: true,
  },
  {
    token: "Data/Small Bold",
    className: "text-data-small-bold",
    font: "Roboto Bold",
    weight: "700",
    size: "14px",
    lineHeight: "20px",
    preview: "TXN-2024-001847",
    tnum: true,
  },
  {
    token: "Data/Small Medium",
    className: "text-data-small-medium",
    font: "Roboto Medium",
    weight: "500",
    size: "14px",
    lineHeight: "20px",
    preview: "TXN-2024-001847",
    tnum: true,
  },
  {
    token: "Data/Small Regular",
    className: "text-data-small-regular",
    font: "Roboto Regular",
    weight: "400",
    size: "14px",
    lineHeight: "20px",
    preview: "TXN-2024-001847",
    tnum: true,
  },
];

export const captionStyles: TypographyStyle[] = [
  {
    token: "Caption/Large Bold",
    className: "text-caption-large-bold",
    font: "Roboto Bold",
    weight: "700",
    size: "12px",
    lineHeight: "16px",
    preview: "Last updated 2 hours ago",
  },
  {
    token: "Caption/Large Medium",
    className: "text-caption-large-medium",
    font: "Roboto Medium",
    weight: "500",
    size: "12px",
    lineHeight: "16px",
    preview: "Last updated 2 hours ago",
  },
  {
    token: "Caption/Large Regular",
    className: "text-caption-large-regular",
    font: "Roboto Regular",
    weight: "400",
    size: "12px",
    lineHeight: "16px",
    preview: "Last updated 2 hours ago",
  },
  {
    token: "Caption/Small Bold",
    className: "text-caption-small-bold",
    font: "Roboto Bold",
    weight: "700",
    size: "11px",
    lineHeight: "14px",
    preview: "Last updated 2 hours ago",
  },
  {
    token: "Caption/Small Medium",
    className: "text-caption-small-medium",
    font: "Roboto Medium",
    weight: "500",
    size: "11px",
    lineHeight: "14px",
    preview: "Last updated 2 hours ago",
  },
  {
    token: "Caption/Small Regular",
    className: "text-caption-small-regular",
    font: "Roboto Regular",
    weight: "400",
    size: "11px",
    lineHeight: "14px",
    preview: "Last updated 2 hours ago",
  },
];

export const typographySections = [
  { title: "Display · TNUM", styles: displayStyles },
  { title: "Heading", styles: headingStyles },
  { title: "Body", styles: bodyStyles },
  { title: "Data · TNUM", styles: dataStyles },
  { title: "Caption", styles: captionStyles },
] as const;

export const typography = {
  display: displayStyles,
  heading: headingStyles,
  body: bodyStyles,
  data: dataStyles,
  caption: captionStyles,
} as const;
